name: GitHub Action Major Release
description: GitHub Action that conditionally creates a floating branch for a major release
inputs:
  major-version:
    required: true
    description: The major version to publish. This will update the branch `v<major-version>` to the current git sha.
  dry-run:
    required: false
    description: Whether to run the action in dry-run mode - no branches will be created or pushed.
    default: "false"
runs:
  using: composite
  steps:
    - name: Create and push branch
      if: inputs.dry-run != 'true'
      shell: bash
      run: |
        echo "Updating branch: v${{ inputs.major-version }}"
        git tag -f v${{ inputs.major-version }}
        git branch -f v${{ inputs.major-version }}
        git push -f origin refs/tags/v${{ inputs.major-version }}
        git push -f origin refs/heads/v${{ inputs.major-version }}
    - name: "Dry-run: Create and push branch"
      if: inputs.dry-run == 'true'
      shell: bash
      run: |
        echo "Updating branch: v${{ inputs.major-version }}"
        echo "  (dry-run)"
        echo "git tag -f v${{ inputs.major-version }}"
        echo "git branch -f v${{ inputs.major-version }}"
        echo "git push -f origin refs/tags/v${{ inputs.major-version }}"
        echo "git push -f origin refs/heads/v${{ inputs.major-version }}"
