name: Release

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # unit tests
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # test action works running from the graph
  action:
    name: Test / Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          dry-run: "true"
          major-version: 123

  release:
    needs:
      - lint
      - test
      - action
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: open-turo/actions-gha/release@v2
